PREFIX ?= fd00::1/64
COOJA_RPL_BR_SERVER_PORT ?= 60001

ifneq ($(PORT),)
	TUNSLIP6_ARGS = -s $(PORT) $(PREFIX)
else
	TUNSLIP6_ARGS = -p $(COOJA_RPL_BR_SERVER_PORT) $(PREFIX)
endif

connect-router: $(TUNSLIP6)
	sudo $(TUNSLIP6) $(TUNSLIP6_ARGS)

connect-router-cooja: $(TUNSLIP6)
	sudo $(TUNSLIP6) -a 127.0.0.1 $(TUNSLIP6_ARGS)
